# Generated by Django 6.0.1 on 2026-01-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='secrets',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
