# Generated by Django 6.0.1 on 2026-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_secrets_id_alter_secrets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Secrets',
        ),
    ]
