# Generated by Django 6.0.1 on 2026-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_secret_delete_secrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('secret', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('p1_tag', models.CharField(max_length=100)),
                ('p1_name', models.CharField(max_length=100)),
                ('p2_tag', models.CharField(max_length=100)),
                ('p2_name', models.CharField(max_length=100)),
                ('p1_score', models.IntegerField()),
                ('p2_score', models.IntegerField()),
                ('center_text', models.CharField(max_length=100)),
            ],
        ),
    ]
