# Generated by Django 6.0.1 on 2026-01-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_scores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
    ]
