# Generated by Django 6.0.1 on 2026-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_rename_scores_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
